### ISSUE TITLE
how to calculate the control volume weighted in the file "jetLES.h5" for a flow filed?

### ISSUE THREAD

**Issue by Afei2021** [HexFluid/spod_python#2]

**Comment by HexFluid** [comment]
Literately use the "control volume" data from the .h5 file as the weight will do.

**Comment by Afei2021** [comment]
> 

Yes, but how to get the original data for the .h5 file of a flow field? I mean how to obtain the weight encapsulated in .h5file

**Comment by HexFluid** [comment]
> > 
> 
> Yes, but how to get the original data for the .h5 file of a flow field? I mean how to obtain the weight encapsulated in .h5file

I suppose you are using a commercial CFD solver. Try to consult the support team instead.

**Comment by Afei2021** [comment]
> 

OK. Got it. Thank you very much.
