### ISSUE TITLE
Temporal evolution of a single mode at specific frequency

### ISSUE THREAD

**Issue by an0nym96** [HexFluid/spod_python#3]
Hi,

thank you for sharing the code. I was interested in visualizing the temporal evolution of a single mode at a specific frequency and visualise it in a similar manner as you have done for the plotting of the reconstructed flow field. Is this possible with the available code or do i need to make modifications to the spod.py file?

Thank you

**Comment by HexFluid** [comment]
> Hi,
> 
> thank you for sharing the code. I was interested in visualizing the temporal evolution of a single mode at a specific frequency and visualise it in a similar manner as you have done for the plotting of the reconstructed flow field. Is this possible with the available code or do i need to make modifications to the spod.py file?
> 
> Thank you

Yes this is possible. You need to reconstruct the flow field using that single mode at one frequency using the in-built function "reconstruct_direct". If you want the mode shape animation only, remove the mode-energy weight term in this function. Afterward, you can reuse the animation postprocess from the example scripts (for 2D only though).
